lints.workspace = true

[package]
name = "gix-hook"
version = "0.0.1"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for discovering and executing git hooks"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
rust-version = "1.85"
include = ["/src/**/*", "/LICENSE-*"]

[lib]
doctest = true

[features]
## Enable support for the SHA-1 hash by forwarding the feature to dependencies.
sha1 = ["gix-config/sha1", "gix-hash/sha1"]
## Enable support for the SHA-256 hash by forwarding the feature to dependencies.
sha256 = ["gix-config/sha256", "gix-hash/sha256"]

[dependencies]
gix-command = { version = "^0.10.0", path = "../gix-command" }
gix-config = { version = "^0.60.0", path = "../gix-config" }
gix-hash = { version = "^0.26.0", path = "../gix-hash" }
gix-validate = { version = "^0.11.3", path = "../gix-validate" }
thiserror = "2.0.18"

[dev-dependencies]
gix-hook = { path = ".", features = ["sha1", "sha256"] }
tempfile = "3.10.0"
