#!/usr/bin/env bash
# Regenerate git-hook-names.txt from git's own canonical hook-name source.
#
# This is a manual maintenance script, not a gix-testtools scripted fixture: it isn't run by
# `cargo test`, and it needs network access, unlike every other fixture in this repository.
# Run it by hand and commit the result when bumping GIT_TAG below.
#
# It extracts names the same way git's own `generate-hooklist.sh` does (see
# https://github.com/git/git/blob/master/generate-hooklist.sh): a hook's name is the line
# immediately preceding a line of one or more `~` characters (an AsciiDoc level-3 heading
# underline) in Documentation/githooks.txt.
set -eu -o pipefail

GIT_TAG=v2.47.0
cd "$(dirname "$0")"

curl --fail --silent --show-error \
	"https://raw.githubusercontent.com/git/git/${GIT_TAG}/Documentation/githooks.txt" |
	sed -n \
		-e '/^~~~~*$/ {x; s/^.*$/&/; p;}' \
		-e 'x' |
	LC_ALL=C sort >git-hook-names.txt.tmp

{
	echo "# Canonical git hook names, extracted from Documentation/githooks.txt at tag ${GIT_TAG}."
	echo "# Generated by refresh-git-hook-names.sh - do not edit by hand."
	cat git-hook-names.txt.tmp
} >git-hook-names.txt
rm git-hook-names.txt.tmp
